security:
    jwt:
        expiration-time: 3600000
        secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
server:
    port: 8005
spring:
    application:
        name: auth-api
    datasource:
        password: secret
        url: jdbc:mysql://localhost:3307/taskdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        
springdoc:
  swagger-ui:  
    max-displayed-tags: 5
    doc-expansion: none
    apisSorter: alpha
    tagsSorter: alpha
    operations-sorter: alpha  
    use-root-path: true
  show-actuator: true
  auto-tag-classes: true
  
management:
   security:
      enabled: false
   endpoints:
     web:
       exposure:
         include: "*"
